# Generated by Django 5.2.14 on 2026-05-20 13:57

import utils.model_validador
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0004_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y%m', validators=[utils.model_validador.validadorPNG]),
        ),
    ]
