# Generated by Django 5.2.14 on 2026-05-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_page_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Marque esse campo se quiser que a pagina seja\n        exibida publicamente'),
        ),
    ]
